name: CI - Ubuntu
on: [pull_request, push]

jobs:
  ci:
    name: Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        libt_version: ["v2.0.4", "v1.2.14"]
        qbt_gui: ["GUI=ON", "GUI=OFF"]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-focal
          sudo apt update
          sudo apt install \
            build-essential cmake ninja-build pkg-config \
            libboost-dev libssl-dev qt515base qt515svg qt515tools zlib1g-dev

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          ccache_options: |
            max_size=2G

      - name: Install libtorrent
        run: |
          git clone --branch ${{ matrix.libt_version }} --depth 1 https://github.com/arvidn/libtorrent.git
          cd libtorrent
          git submodule update --init --recursive
          cmake \
            -B build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -Ddeprecated-functions=OFF \
            --graphviz=cmake-build-dir/target_graph.dot
          cmake --build build
          sudo cmake --install build

      - name: Build qBittorrent
        run: |
          cmake \
            -B build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -D${{ matrix.qbt_gui }} \
            -DVERBOSE_CONFIGURE=ON \
            --graphviz=build/target_graph.dot
          cmake --build build
          sudo cmake --install build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qBittorrent-CI_ubuntu-20.04-x64_${{ matrix.qbt_gui }}_libtorrent-${{ matrix.libt_version }}
          path: |
            build/compile_commands.json
            build/install_manifest.txt
            build/target_graph.dot
            build/qbittorrent
            build/qbittorrent-nox
            libtorrent/cmake-build-dir/compile_commands.json
            libtorrent/cmake-build-dir/target_graph.dot
